version: '3'
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
services:

  db:
    container_name: postgres_db
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BookDB
    ports:
      - "5432:5432"

  app:
    container_name: bookshop
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: bash -c "python manage.py makemigrations --merge --noinput &&
      python manage.py migrate --noinput &&
      python manage.py runserver 0.0.0.0:8000"

  redis:
    container_name: redis_email
    image: redis:5.0.3
    depends_on:
      - helper
    sysctls:
      - net.core.somaxconn=511


  helper:
    image: alpine
    command: sh -c "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
    privileged: true


  celery:
    restart: always
    container_name: celery
    command: celery -A core.celery worker -l INFO
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_NAME=BookDB
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db
      - redis
      - app


