version: '3'
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
services:

  postgres:
    container_name: postgres_db
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BookDB
    ports:
      - "5432:5432"

  app:
    container_name: bookshop
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: bash -c "python manage.py makemigrations --merge --noinput &&
      python manage.py migrate --noinput &&
      python manage.py runserver 0.0.0.0:8000"

