# Generated by Django 3.2 on 2024-04-03 18:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20240403_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Цена')),
                ('publication_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2024)])),
                ('isbn', models.CharField(max_length=17, verbose_name='ISBN')),
                ('page_count', models.IntegerField()),
                ('type_of_cover', models.CharField(choices=[('hard', 'Твердый переплёт'), ('soft', 'Мягкий переплёт'), ('dutch', 'Голланский переплёт')], max_length=5, verbose_name='Тип обложки')),
                ('circulation', models.IntegerField()),
                ('age_limit', models.IntegerField(choices=[(0, '0+'), (6, '6+'), (12, '12+'), (16, '16+'), (18, '18+')], verbose_name='Возрастное ограничение')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.book')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.publisher')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.series')),
            ],
        ),
    ]
