# Generated by Django 3.2 on 2024-04-03 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_bookinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='shop.author'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookAuthor',
        ),
    ]
