# Generated by Django 3.2 on 2024-05-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_bookinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
