# Generated by Django 3.2 on 2024-05-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_bookinfo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
